import { NextRequest, NextResponse } from 'next/server';
import { getSteamAppDetails, validateAppId } from '../../../../utils/steamAPI';
import { generateSteamManifest, formatManifest } from '../../../../utils/manifestGenerator';
import { generateLuaScript } from '../../../../utils/luaGenerator';
import { randomBytes } from 'crypto';

// Simple in-memory storage for demo purposes
// In production, you'd use a proper database
const fileStorage = new Map();

export async function POST(request: NextRequest) {
  try {
    const { appId, discordUserId, discordUsername } = await request.json();

    // Validate input
    if (!validateAppId(appId)) {
      return NextResponse.json(
        { error: 'Invalid App ID' },
        { status: 400 }
      );
    }

    if (!discordUserId) {
      return NextResponse.json(
        { error: 'Discord user ID is required' },
        { status: 400 }
      );
    }

    // Fetch Steam app data
    const appData = await getSteamAppDetails(appId);

    // Generate files
    const manifest = generateSteamManifest(appData);
    const manifestJson = formatManifest(manifest);
    const luaScript = generateLuaScript(appData);

    // Generate unique access key
    const accessKey = randomBytes(16).toString('hex');

    // Calculate expiration (24 hours from now)
    const expiresAt = new Date();
    expiresAt.setHours(expiresAt.getHours() + 24);

    // Store the generated files in memory (for demo)
    const fileData = {
      id: Date.now().toString(),
      userId: discordUserId,
      discordUsername: discordUsername || null,
      steamAppId: appId,
      steamAppName: appData.name,
      manifestContent: manifestJson,
      luaContent: luaScript,
      manifestSize: manifestJson.length,
      luaSize: luaScript.length,
      accessKey: accessKey,
      expiresAt: expiresAt,
      createdAt: new Date()
    };

    fileStorage.set(accessKey, fileData);

    // Create Steamtools-compatible files
    const steamtoolsManifest = createSteamtoolsManifest(manifest, appData);
    const steamtoolsLua = createSteamtoolsLua(luaScript, appData);

    console.log(`Generated files for App ID ${appId} (${appData.name}) - Access Key: ${accessKey}`);

    return NextResponse.json({
      success: true,
      accessKey: accessKey,
      downloadUrl: `/download/${accessKey}`,
      appId: appId,
      appName: appData.name,
      steamtoolsFiles: {
        manifest: steamtoolsManifest,
        lua: steamtoolsLua
      }
    });

  } catch (error) {
    console.error('Error generating files:', error);
    return NextResponse.json(
      { error: 'Failed to generate files: ' + error.message },
      { status: 500 }
    );
  }
}

// Export the storage for use in other routes
export { fileStorage };

function createSteamtoolsManifest(manifest: any, appData: any) {
  // Create a Steamtools-compatible manifest
  return {
    format: "steamtools",
    version: "1.0",
    appid: appData.appId,
    name: appData.name,
    manifest: {
      ...manifest,
      steamtools_metadata: {
        generated_by: "Steam Manifest Generator Bot",
        generated_at: new Date().toISOString(),
        compatible_with: "Steamtools v1.0+",
        export_format: "json"
      }
    }
  };
}

function createSteamtoolsLua(luaScript: string, appData: any) {
  // Add Steamtools compatibility headers
  const steamtoolsHeader = `--[[
  Steamtools Compatible Lua Script
  Generated for: ${appData.name} (${appData.appId})
  Generated by: Steam Manifest Generator Bot
  Generated at: ${new Date().toISOString()}
  
  This script is compatible with Steamtools and can be imported
  directly into your Steamtools project.
]]\n\n`;

  return {
    format: "steamtools",
    version: "1.0",
    appid: appData.appId,
    name: appData.name,
    content: steamtoolsHeader + luaScript,
    metadata: {
      generated_by: "Steam Manifest Generator Bot",
      generated_at: new Date().toISOString(),
      compatible_with: "Steamtools v1.0+",
      language: "lua",
      encoding: "utf-8"
    }
  };
}