import { NextRequest, NextResponse } from 'next/server';

// Simple in-memory storage for file sharing
const fileStorage = new Map<string, any>();

// Add some sample files for immediate testing
const sampleManifest = {
  "appid": 811870,
  "name": "Verlet Swing",
  "state": "eStateAvailable",
  "installdir": "verlet_swing",
  "size": 5000000000,
  "manifest": {
    "gid": "12345678901234567000",
    "size": 25000000,
    "download_size": 1000000000,
    "time_updated": 1634567890,
    "time_created": 1634567200
  }
};

const sampleLua = `--[[
  Steamtools Compatible Lua Script
  Generated for: Verlet Swing (811870)
  Generated by: Steam Manifest Generator Bot
  Generated at: ${new Date().toISOString()}
  
  This script is compatible with Steamtools and can be imported
  directly into your Steamtools project.
]]\n\n--[[
    Steam App Lua Script Generator
    Generated for: Verlet Swing
    App ID: 811870
    Developer: Blue Brain Games s.r.o.
    Publisher: Blue Brain Games s.r.o.
    Release Date: 24 Sep, 2018
    Genres: Action, Indie
    Generated on: ${new Date().toISOString()}
    
    This script provides basic game development functionality
    and utilities for Steam integration.
]]\n\n-- Game configuration
local GameConfig = {
    name = "Verlet Swing",
    appId = 811870,
    version = "1.0.0",
    developer = "Blue Brain Games s.r.o.",
    publisher = "Blue Brain Games s.r.o.",
    releaseDate = "24 Sep, 2018",
    genres = {"Action", "Indie"}
}

-- Steam integration module
local Steam = {}

function Steam.initialize()
    print("Initializing Steam for " .. GameConfig.name)
    print("App ID: " .. GameConfig.appId)
    
    if GameConfig.appId then
        print("✓ Steam API initialized successfully")
        return true
    else
        print("✗ Failed to initialize Steam API")
        return false
    end
end

function Steam.getAchievements()
    return {
        "first_launch",
        "complete_tutorial", 
        "reach_level_10",
        "find_all_secrets",
        "speedrun_complete",
        "perfectionist",
        "explorer",
        "master_player"
    }
end

-- Game state management
local GameState = {
    currentLevel = 1,
    playerHealth = 100,
    playerScore = 0,
    isPaused = false,
    gameTime = 0,
    saveSlots = {}
}

function GameState.save(slot)
    if not slot then slot = 1 end
    
    GameState.saveSlots[slot] = {
        level = GameState.currentLevel,
        health = GameState.playerHealth,
        score = GameState.playerScore,
        gameTime = GameState.gameTime,
        timestamp = os.time()
    }
    
    print("Game saved to slot " .. slot)
    return true
end

function GameState.load(slot)
    if not slot then slot = 1 end
    
    local saveData = GameState.saveSlots[slot]
    if saveData then
        GameState.currentLevel = saveData.level
        GameState.playerHealth = saveData.health
        GameState.playerScore = saveData.score
        GameState.gameTime = saveData.gameTime
        
        print("Game loaded from slot " .. slot)
        return true
    else
        print("No save data found in slot " .. slot)
        return false
    end
end

-- Export modules
return {
    Game = Game,
    GameConfig = GameConfig,
    GameState = GameState,
    Steam = Steam
}`;

// Store sample files
fileStorage.set('demo_manifest_811870', {
  accessKey: 'demo_manifest_811870',
  discordUserId: 'demo_user',
  discordUsername: 'Demo User',
  steamAppId: 811870,
  steamAppName: 'Verlet Swing',
  manifestContent: JSON.stringify(sampleManifest, null, 2),
  luaContent: sampleLua,
  manifestSize: JSON.stringify(sampleManifest).length,
  luaSize: sampleLua.length,
  expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
  createdAt: new Date()
});

export async function GET() {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Steam Manifest Generator - Direct Download</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            min-height: 100vh;
        }
        .container {
            background: rgba(255, 255, 255, 0.1);
            backdrop-filter: blur(10px);
            border-radius: 20px;
            padding: 30px;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
        }
        h1 {
            text-align: center;
            margin-bottom: 30px;
            font-size: 2.5em;
        }
        .download-section {
            background: rgba(255, 255, 255, 0.2);
            border-radius: 10px;
            padding: 20px;
            margin: 20px 0;
            text-align: center;
        }
        .download-button {
            background: #4CAF50;
            color: white;
            border: none;
            padding: 15px 30px;
            border-radius: 10px;
            cursor: pointer;
            font-size: 18px;
            font-weight: bold;
            margin: 10px;
            transition: all 0.3s;
            text-decoration: none;
            display: inline-block;
        }
        .download-button:hover {
            background: #45a049;
            transform: translateY(-2px);
        }
        .file-info {
            background: rgba(0, 0, 0, 0.3);
            padding: 15px;
            border-radius: 5px;
            margin: 10px 0;
            font-family: 'Courier New', monospace;
            font-size: 14px;
        }
        .success {
            border-left: 5px solid #4CAF50;
        }
        .info {
            border-left: 5px solid #2196F3;
        }
        .warning {
            border-left: 5px solid #FF9800;
        }
        .code {
            background: rgba(0, 0, 0, 0.3);
            padding: 15px;
            border-radius: 5px;
            font-family: 'Courier New', monospace;
            white-space: pre-wrap;
            max-height: 300px;
            overflow-y: auto;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🎮 Steam Manifest Generator</h1>
        <h2>📁 Direct File Downloads</h2>
        
        <div class="download-section success">
            <h3>✅ Verlet Swing (811870) - Ready for Download</h3>
            <p>Download the generated Steam manifest and Lua script files:</p>
            
            <a href="/api/direct-download" class="download-button" download="verlet_swing_files.zip">
                📥 Download All Files (ZIP)
            </a>
            
            <div class="file-info">
                <strong>📋 Steam Manifest:</strong> demo_manifest_811870.json<br>
                <strong>🔧 Lua Script:</strong> demo_script_811870.lua
            </div>
        </div>

        <div class="download-section info">
            <h3>🔗 How to Use in Discord</h3>
            <p>Copy and paste these file contents into your Discord bot or use them directly:</p>
            
            <div class="code">
GET /api/direct-download?accessKey=demo_manifest_811870
            </div>
            
            <p>This will give you the complete manifest and Lua files as JSON and text that you can use with your bot!</p>
        </div>

        <div class="download-section warning">
            <h3>⚠️ Important Notes</h3>
            <ul>
                <li>• These are demo files for Verlet Swing</li>
                <li>• Use your own App ID for custom games</li>
                <li>• Files are Steamtools compatible</li>
                <li>• No authentication required</li>
            </ul>
        </div>
    </div>

    <script>
        console.log('🚀 Direct download page loaded');
    </script>
</body>
</html>
  `;

  return new Response(html, {
    headers: { 'Content-Type': 'text/html' }
  });
}

export async function POST(request: NextRequest) {
  try {
    const { action, accessKey } = await request.json();
    
    if (action === 'download' && accessKey) {
      const fileData = fileStorage.get(accessKey);
      
      if (!fileData) {
        return NextResponse.json({ error: 'File not found' }, { status: 404 });
      }
      
      // Return file content for download
      return NextResponse.json({
        success: true,
        manifest: fileData.manifestContent,
        lua: fileData.luaContent,
        appName: fileData.steamAppName,
        appId: fileData.steamAppId
      });
    }
    
    return NextResponse.json({ error: 'Invalid action' }, { status: 400 });
    
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}