const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_ANON_KEY
);

async function createTable() {
  try {
    console.log('🔧 Creating Supabase table...');
    
    // Since we can't run DDL via the client, let's use a different approach
    console.log('📝 Please run this SQL in your Supabase SQL Editor:');
    console.log('🔗 https://xybrjrecphoavhtvcsnn.supabase.co/project/_/sql');
    console.log('\n' + '='.repeat(60));
    
    const sql = `
-- Create table for generated files
CREATE TABLE IF NOT EXISTS generated_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_key VARCHAR(32) UNIQUE NOT NULL,
  discord_user_id VARCHAR(255) NOT NULL,
  discord_username VARCHAR(255),
  steam_app_id INTEGER NOT NULL,
  steam_app_name TEXT NOT NULL,
  manifest_content TEXT NOT NULL,
  lua_content TEXT NOT NULL,
  manifest_size INTEGER NOT NULL,
  lua_size INTEGER NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_generated_files_access_key ON generated_files(access_key);
CREATE INDEX IF NOT EXISTS idx_generated_files_expires_at ON generated_files(expires_at);

-- Enable Row Level Security (RLS)
ALTER TABLE generated_files ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access with access key
CREATE POLICY "Public read access with access key" ON generated_files
  FOR SELECT USING (true);

-- Create policy for insertions (anyone can insert)
CREATE POLICY "Allow insertions" ON generated_files
  FOR INSERT WITH CHECK (true);

-- Create policy for deletions (anyone can delete expired files)
CREATE POLICY "Allow deletions" ON generated_files
  FOR DELETE USING (true);
`;
    
    console.log(sql);
    console.log('='.repeat(60));
    
    console.log('\n🧪 After running the SQL, let\'s test the connection...');
    
    // Test after a delay
    setTimeout(async () => {
      try {
        const { data, error } = await supabase
          .from('generated_files')
          .select('count')
          .limit(1);
        
        if (error) {
          console.log('❌ Table still not found:', error.message);
        } else {
          console.log('✅ Table created successfully!');
          console.log('🎉 Supabase integration is ready!');
        }
      } catch (err) {
        console.error('❌ Test error:', err.message);
      }
    }, 5000);
    
  } catch (error) {
    console.error('❌ Setup error:', error.message);
  }
}

createTable();