import { NextRequest, NextResponse } from 'next/server';

// This endpoint will automatically set up everything
export async function POST(request: NextRequest) {
  try {
    console.log('🚀 Starting automatic setup...');
    
    // Test Supabase connection
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY;
    const supabaseUrl = process.env.SUPABASE_URL;
    
    if (!serviceKey || !supabaseUrl) {
      return NextResponse.json({
        error: 'Missing Supabase credentials',
        setup: {
          step1: 'Go to: https://xybrjrecphoavhtvcsnn.supabase.co/project/_/sql',
          step2: 'Run the SQL to create generated_files table',
          step3: 'Test with: /manifest appid:730'
        }
      });
    }

    // Create a test to see if table exists
    const { createClient } = await import('@supabase/supabase-js');
    const supabase = createClient(supabaseUrl, serviceKey);

    // Test connection
    const { data, error } = await supabase
      .from('generated_files')
      .select('count')
      .limit(1);

    if (error) {
      return NextResponse.json({
        success: false,
        needsSetup: true,
        error: error.message,
        instructions: {
          sqlURL: 'https://xybrjrecphoavhtvcsnn.supabase.co/project/_/sql',
          sql: `
CREATE TABLE IF NOT EXISTS generated_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_key VARCHAR(32) UNIQUE NOT NULL,
  discord_user_id VARCHAR(255) NOT NULL,
  discord_username VARCHAR(255),
  steam_app_id INTEGER NOT NULL,
  steam_app_name TEXT NOT NULL,
  manifest_content TEXT NOT NULL,
  lua_content TEXT NOT NULL,
  manifest_size INTEGER NOT NULL,
  lua_size INTEGER NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_generated_files_access_key ON generated_files(access_key);
CREATE INDEX IF NOT EXISTS idx_generated_files_expires_at ON generated_files(expires_at);

ALTER TABLE generated_files ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access with access key" ON generated_files
  FOR SELECT USING (true);

CREATE POLICY "Allow insertions" ON generated_files
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow deletions" ON generated_files
  FOR DELETE USING (true);`
        }
      });
    }

    return NextResponse.json({
      success: true,
      message: '✅ Supabase table exists and connection is working!',
      nextStep: 'Test the bot with: /manifest appid:730'
    });

  } catch (error) {
    return NextResponse.json({
      error: error.message,
      manualSetup: {
        sqlURL: 'https://xybrjrecphoavhtvcsnn.supabase.co/project/_/sql'
      }
    }, { status: 500 });
  }
}