import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_ANON_KEY!
);

export async function POST() {
  try {
    // Test if table exists by trying to insert a test record
    const testData = {
      access_key: 'test_key_' + Date.now(),
      discord_user_id: 'test_user',
      discord_username: 'test_user',
      steam_app_id: 730,
      steam_app_name: 'Test App',
      manifest_content: '{"test": "data"}',
      lua_content: '-- Test lua script',
      manifest_size: 15,
      lua_size: 18,
      expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString()
    };

    const { data, error } = await supabase
      .from('generated_files')
      .insert(testData)
      .select();

    if (error) {
      // Table doesn't exist, return setup instructions
      return NextResponse.json({
        success: false,
        needsSetup: true,
        error: error.message,
        setupSQL: `
-- Create table for generated files
CREATE TABLE IF NOT EXISTS generated_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_key VARCHAR(32) UNIQUE NOT NULL,
  discord_user_id VARCHAR(255) NOT NULL,
  discord_username VARCHAR(255),
  steam_app_id INTEGER NOT NULL,
  steam_app_name TEXT NOT NULL,
  manifest_content TEXT NOT NULL,
  lua_content TEXT NOT NULL,
  manifest_size INTEGER NOT NULL,
  lua_size INTEGER NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_generated_files_access_key ON generated_files(access_key);
CREATE INDEX IF NOT EXISTS idx_generated_files_expires_at ON generated_files(expires_at);

-- Enable Row Level Security (RLS)
ALTER TABLE generated_files ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access with access key
CREATE POLICY "Public read access with access key" ON generated_files
  FOR SELECT USING (true);

-- Create policy for insertions (anyone can insert)
CREATE POLICY "Allow insertions" ON generated_files
  FOR INSERT WITH CHECK (true);

-- Create policy for deletions (anyone can delete expired files)
CREATE POLICY "Allow deletions" ON generated_files
  FOR DELETE USING (true);`,
        setupURL: 'https://xybrjrecphoavhtvcsnn.supabase.co/project/_/sql'
      });
    }

    // Clean up test data if successful
    if (data && data[0]) {
      await supabase
        .from('generated_files')
        .delete()
        .eq('access_key', testData.access_key);
    }

    return NextResponse.json({
      success: true,
      message: 'Supabase connection is working and table exists!',
      testData: data
    });

  } catch (error) {
    return NextResponse.json({
      success: false,
      error: error.message
    }, { status: 500 });
  }
}