import { NextRequest, NextResponse } from 'next/server';

export async function GET() {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Steam Manifest Generator - Setup Complete</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            min-height: 100vh;
        }
        .container {
            background: rgba(255, 255, 255, 0.1);
            backdrop-filter: blur(10px);
            border-radius: 20px;
            padding: 30px;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
        }
        h1 {
            text-align: center;
            margin-bottom: 30px;
            font-size: 2.5em;
        }
        .status {
            background: rgba(255, 255, 255, 0.2);
            border-radius: 10px;
            padding: 20px;
            margin: 20px 0;
        }
        .success {
            border-left: 5px solid #4CAF50;
        }
        .info {
            border-left: 5px solid #2196F3;
        }
        .warning {
            border-left: 5px solid #FF9800;
        }
        button {
            background: #4CAF50;
            color: white;
            border: none;
            padding: 15px 30px;
            border-radius: 10px;
            cursor: pointer;
            font-size: 16px;
            margin: 10px;
            transition: all 0.3s;
        }
        button:hover {
            background: #45a049;
            transform: translateY(-2px);
        }
        .code {
            background: rgba(0, 0, 0, 0.3);
            padding: 15px;
            border-radius: 5px;
            font-family: 'Courier New', monospace;
            margin: 10px 0;
            overflow-x: auto;
        }
        .step {
            margin: 20px 0;
            padding: 15px;
            background: rgba(255, 255, 255, 0.05);
            border-radius: 10px;
        }
        .test-section {
            text-align: center;
            margin: 30px 0;
        }
        .result {
            margin-top: 20px;
            padding: 15px;
            border-radius: 10px;
            display: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🎮 Steam Manifest Generator</h1>
        <h2>✅ Setup & Integration Status</h2>
        
        <div class="status success">
            <h3>✅ Discord Bot Status: ONLINE</h3>
            <p>Bot is running and generating files with Discord attachments</p>
        </div>

        <div class="status info">
            <h3>🔗 Bot ↔ Website Integration</h3>
            <p><strong id="integration-status">Checking...</strong></p>
        </div>

        <div class="status warning">
            <h3>🗄️ Supabase Database Setup</h3>
            <p><strong id="db-status">Checking...</strong></p>
        </div>

        <div class="step">
            <h3>🚀 Quick Test</h3>
            <p>Test the bot with this command in Discord:</p>
            <div class="code">/manifest appid:730</div>
            <p>This will generate files for Counter-Strike 2</p>
        </div>

        <div class="test-section">
            <button onclick="testAPI()">🧪 Test Website API</button>
            <button onclick="testSupabase()">🗄️ Test Supabase Connection</button>
            <div id="test-result" class="result"></div>
        </div>

        <div class="step">
            <h3>📋 Manual Setup Steps (if needed)</h3>
            <p><strong>1. Create Supabase Table:</strong></p>
            <div class="code">
CREATE TABLE IF NOT EXISTS generated_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_key VARCHAR(32) UNIQUE NOT NULL,
  discord_user_id VARCHAR(255) NOT NULL,
  discord_username VARCHAR(255),
  steam_app_id INTEGER NOT NULL,
  steam_app_name TEXT NOT NULL,
  manifest_content TEXT NOT NULL,
  lua_content TEXT NOT NULL,
  manifest_size INTEGER NOT NULL,
  lua_size INTEGER NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_generated_files_access_key ON generated_files(access_key);
ALTER TABLE generated_files ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access with access key" ON generated_files FOR SELECT USING (true);
CREATE POLICY "Allow insertions" ON generated_files FOR INSERT WITH CHECK (true);
            </div>
            <p><strong>2. Run SQL at:</strong> <a href="https://xybrjrecphoavhtvcsnn.supabase.co/project/_/sql" target="_blank">Supabase SQL Editor</a></p>
        </div>

        <div class="status info">
            <h3>🎯 Current Functionality</h3>
            <ul>
                <li>✅ Discord bot generates files locally</li>
                <li>✅ Files sent as Discord attachments</li>
                <li>✅ Steamtools compatibility</li>
                <li>🔄 Website integration (pending Supabase setup)</li>
                <li>🔄 Download links (pending Supabase setup)</li>
            </ul>
        </div>
    </div>

    <script>
        async function testAPI() {
            const result = document.getElementById('test-result');
            result.style.display = 'block';
            result.className = 'result';
            result.innerHTML = '🔄 Testing API...';

            try {
                const response = await fetch('/api/generate', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        appId: 730,
                        discordUserId: 'test_user',
                        discordUsername: 'test_user'
                    })
                });

                const data = await response.json();
                
                if (data.success) {
                    result.className = 'result success';
                    result.innerHTML = \`
                        ✅ API Working!
                        <br>Access Key: \${data.accessKey}
                        <br>Storage: \${data.storage || 'memory'}
                        <br><a href="\${data.downloadUrl}" target="_blank">🔗 Test Download Link</a>
                    \`;
                } else {
                    result.className = 'result warning';
                    result.innerHTML = \`❌ API Error: \${data.error}\`;
                }
            } catch (error) {
                result.className = 'result warning';
                result.innerHTML = \`❌ Connection Error: \${error.message}\`;
            }
        }

        async function testSupabase() {
            const result = document.getElementById('test-result');
            result.style.display = 'block';
            result.className = 'result';
            result.innerHTML = '🔄 Testing Supabase...';

            try {
                const response = await fetch('/api/setup-supabase', {
                    method: 'POST'
                });

                const data = await response.json();
                
                if (data.success) {
                    result.className = 'result success';
                    result.innerHTML = '✅ Supabase connection working!';
                    document.getElementById('db-status').textContent = 'CONNECTED ✅';
                } else {
                    result.className = 'result warning';
                    result.innerHTML = \`⚠️ Supabase needs setup: \${data.error}\`;
                    document.getElementById('db-status').textContent = 'NEEDS SETUP ⚠️';
                }
            } catch (error) {
                result.className = 'result warning';
                result.innerHTML = \`❌ Supabase Error: \${error.message}\`;
                document.getElementById('db-status').textContent = 'CONNECTION FAILED ❌';
            }
        }

        // Auto-check on load
        window.onload = function() {
            document.getElementById('integration-status').textContent = 'PARTIAL - Bot works, website integration pending';
            document.getElementById('db-status').textContent = 'UNKNOWN - Click test button';
        };
    </script>
</body>
</html>
  `;

  return new Response(html, {
    headers: { 'Content-Type': 'text/html' }
  });
}